CREATE TABLE IF NOT EXISTS product_docs (
  tenant_id BIGINT UNSIGNED NOT NULL,
  product_key VARCHAR(255) NOT NULL,
  product_json JSON NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (tenant_id, product_key)
) ENGINE=InnoDB;
